# Generated by Django 5.0.6 on 2024-06-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='City Unknown', max_length=100),
        ),
    ]
