# Generated by Django 5.0.6 on 2024-06-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraddress_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='landmark',
        ),
    ]
