# Generated by Django 5.0.6 on 2024-07-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_useraddress_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(default='shivakumar', max_length=150),
            preserve_default=False,
        ),
    ]
