# Generated by Django 5.0.6 on 2024-07-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useraddress_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='phone',
        ),
    ]
