# Generated by Django 5.0.6 on 2024-06-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='category_images'),
        ),
    ]
