# Generated by Django 5.0.6 on 2024-06-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_rename_model_code_size_size_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
