# Generated by Django 5.0.6 on 2024-06-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_remove_products_size'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product_sku',
            table='product_sku',
        ),
    ]
