# Generated by Django 5.0.6 on 2024-06-18 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cartproductsize', to='adminside.size'),
            preserve_default=False,
        ),
    ]
