# Generated by Django 5.0.6 on 2024-06-21 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0012_alter_cart_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productwishlist', to='adminside.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Wishlist',
            },
        ),
    ]
