# Generated by Django 5.0.6 on 2024-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0013_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sku',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
