# Generated by Django 5.0.6 on 2024-07-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_order_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_items',
            old_name='price',
            new_name='total_price',
        ),
    ]
