# Generated by Django 5.0.6 on 2024-07-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0017_order_payment_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Order_details',
        ),
        migrations.AlterModelTable(
            name='order_items',
            table='order_items',
        ),
    ]
