# Generated by Django 5.0.6 on 2024-07-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0018_alter_order_table_alter_order_items_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
        ),
    ]
