# Generated by Django 5.0.7 on 2024-07-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0022_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
