# Generated by Django 5.0.7 on 2024-07-17 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0027_order_address_city_order_address_house_no_and_more'),
        ('users', '0010_alter_useraddress_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderAddress', to='users.useraddress'),
        ),
    ]
