# Generated by Django 5.0.7 on 2024-07-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0028_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderedproductsize', to='adminside.size'),
        ),
    ]
