# Generated by Django 5.0.7 on 2024-07-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0030_category_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(blank=True, default='null', null=True, upload_to='banner_images')),
            ],
            options={
                'db_table': 'Banner',
            },
        ),
    ]
